version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:12
    steps:
      - checkout
      - restore_cache:
          keys: [cache]
      - run: 
          name: Build
          command: ./mvnw package
      - save_cache:
          paths: [~/.m2]
          key: cache
workflows:
  version: 2
  build:
    jobs:
      - build