---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install docker
      package: name=docker state=present
    - name: install pip
      package: name=pip state=present
    - name: install docker-py
      pip: name=docker-py
